### ISSUE TITLE
Add state-graph description of battery control in Modelica

### ISSUE THREAD

**Issue by YangyangFu** [lambtt/resilient-building-control#2]
We need add a state-graph representation of battery control for building and grid energy systems. The following items need to be added:

- [x] a schematic figure of the control logic represented as state graph
- [x] a modelica implementation of the control logic using the state-graph package

Please branch `issue2_stateGraph_batteryControl`.

**Comment by lambtt** [comment]
Finished the control logic using the state-graph package:

- The control logic's every mode switch has been tested in Modelica Model: mode_switch_test (given different PVpower, SOC and Load). 

- And I have compared the results between state-graph(wait time=0 s) with no state-graph (old version: wait time=0 s) 

- After test, I changed wait time from 0s to 600 s.

Merged the branch `issue2_stateGraph_batteryControl` and the branch `master`.
